# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to=b''),
        ),
    ]
