# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-10 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_auto_20200610_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='musicas/'),
        ),
    ]
